apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-charts.fullname" . }}
  labels:
    {{- include "backend-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      nodePort: 30001
      targetPort: http
      protocol: TCP
      name: http
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: master-queue
  selector:
    {{- include "backend-charts.selectorLabels" . | nindent 4 }}
