volumes:
  mongodb-vol:

services:
  backend:
    build:
      context: ./backend
    container_name: backend-fastapi
    volumes:
      - ./backend/app:/code/app
    environment:
      MONGODB_URI: "mongodb://root:password@mongodb:27017"
      DATABASE_NAME: vm-test
    ports:
      - '8080:80'
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend-react
    environment:
      REACT_APP_BACKEND: http://192.168.1.11:8080
    ports:
      - '3000:3000'
    depends_on:
      - backend
  
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  master:
    build:
      context: ./vms
      dockerfile: Dockerfile.master
    container_name: master-vm
    ports:
      - '6080:6081'
    volumes:
      - ./vms/code:/home/ubuntu/code
      - ./vms/images:/home/ubuntu/code/images
    shm_size: '2gb'
    environment:
      VM_NAME : 'vm_master'
      RESOLUTION: '800x600'
      MASTER_QUEUE: backend:6000
      GROUP: group_fr
      EMAIL: 
      PASSWORD: 
    depends_on:
      - backend
  
  worker:
    build:
      context: ./vms
      dockerfile: Dockerfile.worker
    container_name: worker-vm-1
    ports:
      - '6081:6081'
    volumes:
      - ./vms/code:/home/ubuntu/code
      - ./vms/images:/home/ubuntu/code/images
    shm_size: '2gb'
    environment:
      VM_NAME : 'vm1'
      RESOLUTION: '800x600'
      MOUSE_QUEUE: master:5000
      MASTER_QUEUE: backend:6000
      GROUP: group_fr
      EMAIL: 
      PASSWORD:
    depends_on:
      - master
      - backend

  worker2:
    build:
      context: ./vms
      dockerfile: Dockerfile.worker
    container_name: worker-vm-2
    ports:
      - '6082:6081'
    volumes:
    - ./vms/code:/home/ubuntu/code
    - ./vms/images:/home/ubuntu/code/images
    shm_size: '2gb'
    environment:
      VM_NAME : 'vm2'
      RESOLUTION: '800x600'
      MOUSE_QUEUE: master:5000
      MASTER_QUEUE: backend:6000
      GROUP: group_fr
      EMAIL:
      PASSWORD:
    depends_on:
      - master
      - backend
  