apiVersion: v1
kind: PersistentVolume
metadata:
  name: vm-manage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath:
    path: /tmp/vm-manage-pv