apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-manage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: vm-manage-pv