FROM ondinhk/vm-base:proxy-v2

COPY ./code /home/ubuntu/code

ENTRYPOINT ["sh","-c", "/startup.sh & sleep 30 && export DISPLAY=:1 && python /home/ubuntu/code/mouse/client.py & sleep 30 && export DISPLAY=:1 && python /home/ubuntu/code/worker/worker.py"]
