apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-charts.fullname" . }}
  labels:
    {{- include "frontend-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "frontend-charts.selectorLabels" . | nindent 4 }}
